(
  ("https://ianthehenry.com/feed.xml" lcolonq)
  ("https://blog.fogus.me/feed/" lcolonq)
  ("https://xeiaso.net/blog.rss" lcolonq)
  ("https://tylercipriani.com/blog/index.rss" lcolonq)
  ("https://palant.info/rss.xml" lcolonq)
  ("https://shallowsky.com/blog/index.atom" lcolonq)
  ("https://cadence.moe/blog/atom.xml?limit=30" lcolonq)
  ("https://joeyh.name/blog/index.rss" lcolonq)
  ("https://www.copetti.org/index.xml" lcolonq)
  ("https://sachachua.com/blog/feed" lcolonq)
  ("https://protesilaos.com/codelog.xml" lcolonq)
  ("https://jakob.space/feed.xml" lcolonq)
  ("https://taylor.town/feed.xml" lcolonq)
  ("https://bernsteinbear.com/feed.xml" lcolonq)
  ("https://blog.zarfhome.com/feeds/posts/default.rss" lcolonq)
  ("https://www.gamingonlinux.com/article_rss.php" azrhyga)
  ("https://jvns.ca/atom.xml" cristober)
  ("https://www.ralfj.de/blog/feed.xml" devts_de)
  ("https://jakeout.com/posts/rss.xml" jakeout)
  ("https://www.boristhebrave.com/feed/" bvnanana)
  ("https://palaiologos.rocks/index.xml" pralkarz)
  ("https://hackaday.com/blog/feed" chaoticquixotic)
  ("https://peetseater.space/blag/feed.xml" peetseater)
  ("https://blog.cr.yp.to/feed.application=xml" devts_de)
  ("https://blog.frost.kiwi/feed.xml" pralkarz)
  ("https://curiouscoding.nl/index.xml" pralkarz)
  ("https://phys.org/rss-feed/breaking/" jakeout)
  ("https://www.theremingoat.com/blog?format=rss" jakeout)
  ("https://www.bitonicsoft.com/index.xml" bytomancer)
  ("https://www.bytomancer.com/index.xml" bytomancer)
  ("https://knifesteelnerds.com/feed/" jakeout)
  ("https://cybercat.institute/feed.xml" ABipolarCarp123)
  ("https://www.shutupandsitdown.com/feed/" jakeout)
  ("https://qntm.org/rss.php" fighting_annelids)
  ("http://www.adriancourreges.com/blog/" a_tension_span)
  ("https://randomascii.wordpress.com/feed/" RealNaesten)
  ("https://fabiensanglard.net/rss.xml" a_tension_span)
  ("https://ftrv.se/posts.rss" krzysckh)
  ("https://ciechanow.ski/atom.xml" Compilingjay)
  ("http://wololo.net/feed" Faeliore)
  ("https://lichess.org/@/Lichess/blog.atom" localtost)
  ("https://faultlore.com/blah/rss.xml" FreeFull)
  ("https://golem.ph.utexas.edu/category/atom10.xml" quantumbohm)
  ("https://kibty.town/blog.rss" Compilingjay)
  ("https://www.cnx-software.com/feed" jakeout)
  ("https://ftrv.se/posts.atom" krzysckh)
  ("https://100r.co/links/rss.xml" krzysckh)
  ("https://grimgrains.com/links/rss.xml" krzysckh)
  ("https://jendrikillner.com/tags/weekly/index.xml" a_tension_span)
  ("https://midnight.pub/feed.xml" krzysckh)
  ("https://lparchive.org/rss" PeetsEater)
  ("https://cvefeed.io/rssfeed/" localtost)
  ("https://matklad.github.io/feed.xml" PJZ_here)
  ("https://people.kernel.org/read/feed/" PJZ_here)
  ("https://sarah.engineer/posts/index.xml" badcop_)
  ("https://izzys.casa/index.xml" bruxisma)
  ("https://guix.gnu.org/feeds/blog.atom" bigbookofbug)
  ("https://erysdren.me/atom.xml" bruxisma)
  ("https://char.lt/blog.rss" sschr15)
  ("https://kidakaka.com/rss/" localtost)
  ("http://www.schneier.com/blog/index.rdf" localtost)
  ("http://www.rhinosecuritylabs.com/blog/feed/" localtost)
  ("http://www.bleepingcomputer.com/feed/" localtost)
  ("http://taosecurity.blogspot.com/atom.xml" localtost)
  ("https://30fps.net/atom.xml" bruxisma)
  ("https://rachelandrew.co.uk/feed" bruxisma)
  ("https://pub.colonq.computer/~sschr15/cgi-bin/blog.rss" sschr15)
  ("https://fluted.omg.lol/rss.xml" fluted)

  ("https://www.youtube.com/feeds/videos.xml?channel_id=UCFcW86JuchB35JyRc8GQrag" lcolonq)
  ("https://www.youtube.com/feeds/videos.xml?channel_id=UCjNErCQgCndSOl6t33m1-nQ" lcolonq)
  ("https://www.youtube.com/feeds/videos.xml?channel_id=UCI9eybCgmaFtbhCdBy8q62Q" lcolonq)
  ("https://www.youtube.com/feeds/videos.xml?channel_id=UCS0dC-YmI5mE62NSLBY6seA" lcolonq)
  ("https://www.youtube.com/feeds/videos.xml?channel_id=UC6sy8jNFDqQiXRH0VozAONg" lcolonq)
  ("https://www.youtube.com/feeds/videos.xml?channel_id=UCNQJqvSXfDBOd9spve8doWw" lcolonq)
  ("https://www.youtube.com/feeds/videos.xml?channel_id=UC9UJ7FU85pQujXTZkfUq24g" lcolonq)
  ("https://www.youtube.com/feeds/videos.xml?channel_id=UCAYF6ZY9gWBR1GW3R7PX7yw" lcolonq)
  ("https://www.youtube.com/feeds/videos.xml?channel_id=UCo0-VCHchPIG3JtJlIQnFew" lcolonq)
  ("https://www.youtube.com/feeds/videos.xml?channel_id=UCEp20NgOZHmgWdbQdHSxgjw"
    colinahscopy_)
  ("https://www.youtube.com/feeds/videos.xml?channel_id=UC5I2hjZYiW9gZPVkvzM8_Cw"
    colinahscopy_)
  ("https://www.youtube.com/feeds/videos.xml?channel_id=UCRS3_dsBPTN8VVyu0j3Xnsw"
    colinahscopy_)
  ("https://www.youtube.com/feeds/videos.xml?channel_id=UChrYe70o7NmDioL02PRVWVg"
    colinahscopy_)
  ("https://www.youtube.com/feeds/videos.xml?channel_id=UCmEmX_jw_pRp5UbAdzkZq-g"
    The0x539)
  ("https://www.youtube.com/feeds/videos.xml?channel_id=UC_iD0xppBwwsrM9DegC5cQQ"
    freefull)
  ("https://www.youtube.com/feeds/videos.xml?channel_id=UCYM5uzz7xnY8_S9iBM-TVGA"
    steeledshield)
  ("https://www.youtube.com/feeds/videos.xml?channel_id=UCivA7_KLKWo43tFcCkFvydw"
    watchmakering)
  ("https://www.youtube.com/feeds/videos.xml?channel_id=UCr0f-r1bRexAZK8sWyk4NJA"
    jakeout)
  ("https://www.youtube.com/feeds/videos.xml?channel_id=UCXIkr0SRTnZO4_QpZozvCCA"
    fighting_annelids)
  ("https://www.youtube.com/feeds/videos.xml?channel_id=UC7M-Wz4zK8oikt6ATcoTwBA"
    a_tension_span)
  ("https://www.youtube.com/feeds/videos.xml?channel_id=UCjdHbo8_vh3rxQ-875XGkvw"
    steeledshield)
  ("https://www.youtube.com/feeds/videos.xml?channel_id=UCze-aBdbS0B_oJMPvCs85dA"
    khlorghaal)
  ("https://www.youtube.com/feeds/videos.xml?channel_id=UCQG40havu4kNpB4pxUDQhYQ"
    sohakunni)
  ("https://www.youtube.com/feeds/videos.xml?channel_id=UC3azLjQuz9s5qk76KEXaTvA"
    sohakunni)
  ("https://www.youtube.com/feeds/videos.xml?channel_id=UCx6cailiCkg_mlMM7JX5yfA"
    Colinahscopy_)
  ("https://www.youtube.com/feeds/videos.xml?channel_id=UCTAfm-YD2M9xzvbYvRc5ttA"
    partycatlol)
  ("https://www.youtube.com/feeds/videos.xml?channel_id=UCfAvImNHaevXE7cAmHSOQDQ"
    a_tension_span)
  ("https://www.youtube.com/feeds/videos.xml?channel_id=UCMAJEIm9a_NGhD7BgWDMoXw"
    steeledshiel)
  ("https://www.youtube.com/feeds/videos.xml?channel_id=UCZXW8E1__d5tZb-wLFOt8TQ"
    joker_dan)
  ("https://www.youtube.com/feeds/videos.xml?channel_id=UC7qFfPYl0t8Cq7auyblZqxA"
    rubyynt)
  ("https://www.youtube.com/feeds/videos.xml?channel_id=UCaXh9z3or5QbM0HPGen2Quw"
    a_tension_span)
  ("https://www.youtube.com/feeds/videos.xml?channel_id=UCtHaxi4GTYDpJgMSGy7AeSw"
    octorinski)
  ("https://www.youtube.com/feeds/videos.xml?channel_id=UCMBmwfaemvLEUzwe965OqhA"
    bvnanana)
  ("https://www.youtube.com/feeds/videos.xml?channel_id=UConVfxXodg78Tzh5nNu85Ew"
    a_tension_span)
  ("https://www.youtube.com/feeds/videos.xml?channel_id=UCS0N5baNlQWJCUrhCEo8WlA"
    mental_equilibrist)
  ("https://www.youtube.com/feeds/videos.xml?channel_id=UC7UukP_hxrOsrwHrcHxOxxg"
    cristober)
  ("https://www.youtube.com/feeds/videos.xml?channel_id=UCKTehwyGCKF-b2wo0RKwrcg"
    cristober)
  ("https://www.youtube.com/feeds/videos.xml?channel_id=UCNLRcEn78Vc62C3GkMvBgtA"
    lumistatics)
  ("https://www.youtube.com/feeds/videos.xml?channel_id=UCc3FpdfUKkpgt6Sc4_wiV_Q"
    gtfrvz)
  ("https://www.youtube.com/feeds/videos.xml?channel_id=UCYO_jab_esuFRV4b17AJtAw"
    a_tension_span)
  ("https://www.youtube.com/feeds/videos.xml?channel_id=UCilouT5irlCNn2imcCDhhJQ"
    steeledshield)
  ("https://www.youtube.com/feeds/videos.xml?channel_id=UCtM5z2gkrGRuWd0JQMx76qA"
    yukievt)
  ("https://www.youtube.com/feeds/videos.xml?channel_id=UCworsKCR-Sx6R6-BnIjS2MA"
    NOCTU4)
  ("https://www.youtube.com/feeds/videos.xml?channel_id=UCeRXQ_B5WZD3yjPly45myvg"
    zment)
  ("https://www.youtube.com/feeds/videos.xml?channel_id=UCE4xstUnu0YmkG-W9_PyYrQ"
    zment)
  ("https://www.youtube.com/feeds/videos.xml?channel_id=UCrqM0Ym_NbK1fqeQG2VIohg"
    rubyynt)
  ("https://www.youtube.com/feeds/videos.xml?channel_id=UCvw6Y1kr_8bp6B5m1dqNyiw"
    Faeliore)
  ("https://www.youtube.com/feeds/videos.xml?channel_id=UCzp1RaZ3HmejKl723qlKOAw"
    steeledshield)
  ("https://www.youtube.com/feeds/videos.xml?channel_id=UCG7yIWtVwcENg_ZS-nahg5g"
    cristober)
  ("https://www.youtube.com/feeds/videos.xml?channel_id=UC6_J0wZdqcoRVs0Mck922SQ"
    cristober)
  ("https://www.youtube.com/feeds/videos.xml?channel_id=UCSju5G2aFaWMqn-_0YBtq5A"
    cristober)
  ("https://www.youtube.com/feeds/videos.xml?channel_id=UCV5vCi3jPJdURZwAOO_FNfQ"
    cristober)
  ("https://www.youtube.com/feeds/videos.xml?channel_id=UCrv269YwJzuZL3dH5PCgxUw"
    FreeFull)
  ("https://www.youtube.com/feeds/videos.xml?channel_id=UCFFeNyzCEQDS4KCecugmotg"
    ABipolarCarp123)
  ("https://www.youtube.com/feeds/videos.xml?channel_id=UC8uT9cgJorJPWu7ITLGo9Ww"
    anothercommoninternetuser)
  ("https://www.youtube.com/feeds/videos.xml?channel_id=UC6gARF3ICgaLfs3o2znuqXA"
    zment)
  ("https://www.youtube.com/feeds/videos.xml?channel_id=UCoxcjq-8xIDTYp3uz647V5A"
    jakeout)
  ("https://www.youtube.com/feeds/videos.xml?channel_id=UCqbYqJdvCB_tNjtppgFuN8A"
    khlorghaal)
  ("https://www.youtube.com/feeds/videos.xml?channel_id=UC3Oi3oA33qlzADMX5fWhOkQ"
    ellg)
  ("https://www.youtube.com/feeds/videos.xml?channel_id=UCeEf90AEmmxaQs5BUkHqR3Q"
    zment)
  ("https://www.youtube.com/feeds/videos.xml?channel_id=UCPb7xe-MQ0KiJpaKBWFZtTA"
    moopogen1)
  ("https://www.youtube.com/feeds/videos.xml?channel_id=UCtUbO6rBht0daVIOGML3c8w"
    PeetsEater)
  ("https://www.youtube.com/feeds/videos.xml?channel_id=UCVXYr7yCUsfamWMf1N1qRJQ"
    PeetsEater)
  ("https://www.youtube.com/feeds/videos.xml?channel_id=UCPjFa_UZBUDzdJTIEdyGjIQ"
    yukievt)
  ("https://www.youtube.com/feeds/videos.xml?channel_id=UCJXa3_WNNmIpewOtCHf3B0g"
    PeetsEater)
  ("https://www.youtube.com/feeds/videos.xml?channel_id=UCKTwTio3tOv713CnIcxyLhA"
    PeetsEater)
  ("https://www.youtube.com/feeds/videos.xml?channel_id=UCvjgXvBlbQiydffZU7m1_aw"
    zment)
  ("https://www.youtube.com/feeds/videos.xml?channel_id=UCmtyQOKKmrMVaKuRXz02jbQ"
    zment)
  ("https://www.youtube.com/feeds/videos.xml?channel_id=UC9-y-6csu5WGm29I7JiwpnA"
    camden82002)
  ("https://www.youtube.com/feeds/videos.xml?channel_id=UCYg6qFXDE5SGT_YXhuJPU0A"
    wyndupboy)
  ("https://www.youtube.com/feeds/videos.xml?channel_id=UCwRqWnW5ZkVaP_lZF7caZ-g"
    PeetsEater)
  ("https://www.youtube.com/feeds/videos.xml?channel_id=UC8A3Zig-dNx2kZmy1FovTEA"
    PeetsEater)
  ("https://www.youtube.com/feeds/videos.xml?channel_id=UCKSrgKjevPmNZxCAyTZP5cQ"
    a_tension_span)
  ("https://www.youtube.com/feeds/videos.xml?channel_id=UCKetFmtqdh-kn915crdf72A"
    a_tension_span)
  ("https://www.youtube.com/feeds/videos.xml?channel_id=UCeR0n8d3ShTn_yrMhpwyE1Q"
    peetseater)
  ("https://www.youtube.com/feeds/videos.xml?channel_id=UCCtYdNBm-8C_wZk0n6u8VnQ"
    BrighterMalphon)
  ("https://www.youtube.com/feeds/videos.xml?channel_id=UCsSsgPaZ2GSmO6il8Cb5iGA"
    ellg)
  ("https://www.youtube.com/feeds/videos.xml?channel_id=UC8ge7La_vq48PVEmR-DJ5Wg"
    zment)
  ("https://www.youtube.com/feeds/videos.xml?channel_id=UCJ0-OtVpF0wOKEqT2Z1HEtA"
    zment)
  ("https://www.youtube.com/feeds/videos.xml?channel_id=UCz8XK-lpjoZxOSFRlQyM28Q"
    zment)
  ("https://www.youtube.com/feeds/videos.xml?channel_id=UCOyJD0RHtF_77_oAf5tT1nQ"
    tomaterr)
  ("https://www.youtube.com/feeds/videos.xml?channel_id=UCVpankR4HtoAVtYnFDUieYA"
    elysiumplain)
  ("https://www.youtube.com/feeds/videos.xml?channel_id=UC84QVg2z9jms4tBkfe2h91w"
    zarithya)
  ("https://www.youtube.com/feeds/videos.xml?channel_id=UCm87i_qG_B-rRvG7NWqyVLw"
    tomaterr)
  ("https://www.youtube.com/feeds/videos.xml?channel_id=UCNypeTQAfb2pBA-BLPYK0kg"
    irek32)
  ("https://www.youtube.com/feeds/videos.xml?channel_id=UCtGoikgbxP4F3rgI9PldI9g"
    liquidcake1)
  ("https://www.youtube.com/feeds/videos.xml?channel_id=UCS-WzPVpAAli-1IfEG2lN8A" 
    fluted)
  ("https://www.youtube.com/feeds/videos.xml?channel_id=UCf_suVrG2dA5BTjJhNLwthQ" 
    fluted)
  )
